apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: tffood-api
  name: tffood-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: tffood-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: tffood-api
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  service: tffood-api
              topologyKey: "kubernetes.io/hostname"
      containers:
        - image: maksim1111/tffood-api:latest
          name: tffood-api
          imagePullPolicy: Always
          command: [ "/app/main" ]
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
          volumeMounts:
            - mountPath: /app/storage
              subPath: storage
              name: tffood-api-data
          env:
            - name: DB_PATH
              value: /app/storage/db.sqlite
          envFrom:
            - secretRef:
                name: tffood-api-secrets
      volumes:
        - name: tffood-api-data
          persistentVolumeClaim:
            claimName: tffood-api-data
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: tffood-api
  name: tffood-api
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    service: tffood-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tffood-api
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: tffood-api.mxksim.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tffood-api
                port:
                  number: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tffood-api-data
spec:
  storageClassName: "do-block-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---